<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <AssemblyName>launcher</AssemblyName>
    <RootNamespace>zolsi.cc</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>src\app.manifest</ApplicationManifest>
    <PublishAot>true</PublishAot>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishDir>$(MSBuildThisFileDirectory)publish\</PublishDir>
    <DebugType>none</DebugType>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="skills\**" />
    <None Remove="skills\**" />
    <Compile Remove="hashes\**" />
    <None Remove="hashes\**" />
  </ItemGroup>

</Project>